# Generated by Django 4.2 on 2023-04-18 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('galeria', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='foto',
            name='categoria',
            field=models.CharField(choices=[('NUBULOSA', 'nubulosa'), ('ESTRELA', 'estrela'), ('GALAXIA', 'galaxia'), ('PLANETA', 'planeta')], default='', max_length=100),
        ),
    ]
